services:
  backend:
    build: .
    container_name: ah-aihms-backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV={FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URI=${MONGODB_URI}
