[tool.black]
line-length = 100
target-version = ["py311"]
exclude = '''
/(
    \.venv
  | __pycache__
  | migrations
)/
'''
extend-exclude = "app/models/__init__.py"

[tool.isort]
profile = "black"
line_length = 100
skip = [".venv", "migrations", "__pycache__", "app/models/__init__.py"]

[tool.ruff]
line-length = 100
exclude = [".venv", "migrations", "__pycache__", "app/models/__init__.py"]
target-version = "py311"
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.coverage.report]
fail_under = 60